### ISSUE TITLE
Windows machines out of disk space

### ISSUE THREAD

**Issue by retronym** [scala/scala-jenkins-infra#168]
https://scala-ci.typesafe.com/computer/jenkins-worker-windows-publish/executors/0/causeOfDeath

```
java.io.IOException: Failed to create a temporary file in /var/lib/jenkins/jobs/scala-2.12.x-integrate-windows
    at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:68)
    at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:55)
    at hudson.util.TextFile.write(TextFile.java:118)
    at hudson.model.Job.saveNextBuildNumber(Job.java:290)
    at hudson.model.Job.assignBuildNumber(Job.java:348)
    at hudson.model.Run.<init>(Run.java:290)
    at hudson.model.AbstractBuild.<init>(AbstractBuild.java:170)
    at hudson.model.Build.<init>(Build.java:92)
    at hudson.model.FreeStyleBuild.<init>(FreeStyleBuild.java:34)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:177)
    at hudson.model.AbstractProject.newBuild(AbstractProject.java:1011)
    at hudson.model.AbstractProject.createExecutable(AbstractProject.java:1210)
    at hudson.model.AbstractProject.createExecutable(AbstractProject.java:144)
    at hudson.model.Executor$1.call(Executor.java:328)
    at hudson.model.Executor$1.call(Executor.java:310)
    at hudson.model.Queue._withLock(Queue.java:1251)
    at hudson.model.Queue.withLock(Queue.java:1189)
    at hudson.model.Executor.run(Executor.java:310)
Caused by: java.io.IOException: No space left on device
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createTempFile(File.java:2001)
    at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:66)
    ... 21 more
```

**Comment by retronym** [comment]
![image](https://cloud.githubusercontent.com/assets/65551/13735566/132c43d2-e9f7-11e5-8f43-d25dbb039a87.png)

:ambulance:  @SethTisue @adriaanm

**Comment by SethTisue** [comment]
this is doing OK at the moment.

I forget what I, or somebody, might have deleted to make space — probably the stuff in #78.

I manually check the disk space on all of the Jenkins nodes every 5 days. I think we only ran out this time because I was sick for a week and missed my usual check. so, optimistically closing given that #78 remains open.
