### ISSUE TITLE
regression: chef-client fails on jenkins-master

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#231]
```
  * jenkins_plugin[build-flow-plugin] action install
    
    ================================================================================
    Error executing action `install` on resource 'jenkins_plugin[build-flow-plugin]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:245:in `desired_version'
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:141:in `block in <class:JenkinsPlugin>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/scala-jenkins-infra/recipes/_master-config-jenkins.rb
    
     30:   jenkins_plugin plugin
     31: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/scala-jenkins-infra/recipes/_master-config-jenkins.rb:30:in `block in from_file'
    
    jenkins_plugin("build-flow-plugin") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_plugin
      cookbook_name "scala-jenkins-infra"
      recipe_name "_master-config-jenkins"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2017-06-16T19:42:15+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-16T19:42:15+00:00] ERROR: Exception handlers complete
Chef Client failed. 5 resources updated in 29 seconds
[2017-06-16T19:42:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-06-16T19:42:15+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-16T19:42:15+00:00] ERROR: jenkins_plugin[build-flow-plugin] (scala-jenkins-infra::_master-config-jenkins line 30) had an error: NoMethodError: undefined method `[]' for nil:NilClass
[2017-06-16T19:42:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by SethTisue** [comment]
seems helpful/relevant: https://www.coveros.com/chef-undefined-method-for-nilclass/

**Comment by SethTisue** [comment]
oh joy, https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin says "Distribution of This Plugin Has Been Suspended", so that's the cause. "Users should migrate to https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin", it says

**Comment by SethTisue** [comment]
after removing the build flow plugin from `_master-config-jenkins.rb` and re-running `chef-client`...

```text
resolving cookbooks for run list: ["chef-vault", "scala-jenkins-infra::master-init", "scala-jenkins-infra::master-config", "scala-jenkins-infra::master-jenkins", "scala-jenkins-infra::master-scabot"]
Synchronizing Cookbooks:
  - chef-vault (1.3.0)
  - magic_shell (1.0.1)
  - cron (3.0.0)
  - chef-client (7.1.0)
  - logrotate (2.1.0)
  - compat_resource (12.16.3)
  - windows (2.1.1)
  - ohai (4.2.3)
  - ebs (0.3.6)
  - chocolatey (1.1.0)
  - aws (4.1.3)
  - delayed_evaluator (0.2.0)
  - java (1.39.0)
  - apt (4.0.2)
  - jenkins (4.2.1)
  - runit (1.7.0)
  - packagecloud (0.2.5)
  - artifactory (2.0.0)
  - build-essential (7.0.3)
  - ark (2.2.1)
  - seven_zip (2.0.2)
  - mingw (1.2.5)
  - git (4.2.2)
  - git_user (0.3.1)
  - yum-epel (2.1.1)
  - dmg (2.2.2)
  - scala-jenkins-infra (0.5.0)
  - user (0.4.2)
  - ssh_known_hosts (2.0.0)
  - homebrew (2.1.2)
  - partial_search (1.0.8)
  - sbt-extras (0.4.0)
  - nodejs (2.4.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2017-06-19T22:43:00+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2017-06-19T22:43:00+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install (up to date)
[2017-06-19T22:43:01+00:00] WARN: The default aws recipe does nothing. See the readme for information on using the aws resources
[2017-06-19T22:43:01+00:00] WARN: Here we go with the runit service
  Converging 204 resources
  * chef_gem[chef-vault] action install (up to date)
Recipe: scala-jenkins-infra::_init-chef-client
  * magic_shell_environment[SSL_CERT_FILE] action add
  Recipe: <Dynamically Defined Resource>
    * file[/etc/profile.d/SSL_CERT_FILE.sh] action create (up to date)
     (up to date)
Recipe: chef-client::init_service
  * directory[/var/run/chef] action create (up to date)
  * directory[/var/cache/chef] action create (up to date)
  * directory[/var/lib/chef] action create (up to date)
  * directory[/var/log/chef] action create (up to date)
  * directory[/etc/chef] action create (up to date)
  * template[/etc/init.d/chef-client] action create (up to date)
  * template[/etc/sysconfig/chef-client] action create (up to date)
  * service[chef-client] action enable (up to date)
  * service[chef-client] action start (up to date)
Recipe: scala-jenkins-infra::_java_packages
  * yum_package[java-1.7.0-openjdk-devel] action install (up to date)
  * yum_package[java-1.8.0-openjdk-devel] action install (up to date)
Recipe: java::openjdk
  * yum_package[java-1.8.0-openjdk] action install (up to date)
  * yum_package[java-1.8.0-openjdk-devel] action install (up to date)
  * java_alternatives[set-java-alternatives] action set (up to date)
Recipe: java::set_java_home
  * ruby_block[set-env-java-home] action run (skipped due to not_if)
  * directory[/etc/profile.d] action create (up to date)
  * file[/etc/profile.d/jdk.sh] action create (up to date)
Recipe: scala-jenkins-infra::_jvm-select
  * directory[/usr/local/share/jvm/] action create (up to date)
  * cookbook_file[jvm-select] action create (up to date)
Recipe: scala-jenkins-infra::_config-ebs
  * aws_ebs_volume[/dev/sdj] action create (up to date)
  * aws_ebs_volume[/dev/sdj] action attach (up to date)
  * execute[mkfs] action runext4
 (skipped due to not_if)
  * directory[/var/lib/jenkins] action create (up to date)
  * mount[/var/lib/jenkins] action mount (up to date)
  * mount[/var/lib/jenkins] action enable (up to date)
  * aws_ebs_volume[/dev/sdk] action create (up to date)
  * aws_ebs_volume[/dev/sdk] action attach (up to date)
  * execute[mkfs] action runext4
 (skipped due to not_if)
  * directory[/var/lib/artifactory] action create (up to date)
  * mount[/var/lib/artifactory] action mount (up to date)
  * mount[/var/lib/artifactory] action enable (up to date)
Recipe: jenkins::_master_war
  * linux_user[jenkins] action create (up to date)
  * group[jenkins] action create (up to date)
  * directory[/var/lib/jenkins] action create (up to date)
  * directory[/var/log/jenkins] action create (up to date)
Recipe: runit::default
  * service[runit] action nothing (skipped due to action :nothing)
  * execute[start-runsvdir] action nothing (skipped due to action :nothing)
  * execute[runit-hup-init] action nothing (skipped due to action :nothing)
  * packagecloud_repo[imeyer/runit] action add
    * yum_package[pygpgme] action install (up to date)
    * log[pygpgme_warning] action write (skipped due to not_if)
    * ruby_block[disable repo_gpgcheck if no pygpgme] action run (skipped due to not_if)
    * template[/etc/yum.repos.d/imeyer_runit.repo] action create (up to date)
    * execute[yum-makecache-imeyer_runit] action nothing (skipped due to action :nothing)
    * ruby_block[yum-cache-reload-imeyer_runit] action nothing (skipped due to action :nothing)
     (up to date)
  * yum_package[runit] action install (up to date)
Recipe: jenkins::_master_war
  * remote_file[/var/lib/jenkins/jenkins.war] action create (up to date)
Recipe: <Dynamically Defined Resource>
  * service[jenkins] action nothing (skipped due to action :nothing)
Recipe: jenkins::_master_war
  * runit_service[jenkins] action enable
    * directory[/etc/sv/jenkins] action create (up to date)
    * template[/etc/sv/jenkins/run] action create (up to date)
    * directory[/etc/sv/jenkins/log] action create (up to date)
    * directory[/etc/sv/jenkins/log/main] action create (up to date)
    * template[/etc/sv/jenkins/log/run] action create (up to date)
    * template[/etc/sv/jenkins/log/config] action create (up to date)
    * directory[/etc/sv/jenkins/env] action create (up to date)
    * ruby_block[zap extra env files] action run (skipped due to only_if)
    * directory[/etc/sv/jenkins/control] action create (up to date)
    * link[/etc/init.d/jenkins] action create (up to date)
    * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
    * link[/etc/service/jenkins] action create (up to date)
     (up to date)
Recipe: scala-jenkins-infra::_master-init-jenkins
  * directory[/var/lib/jenkins/users] action create (up to date)
  * directory[/var/lib/jenkins/users/chef/] action create (up to date)
  * template[/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml] action create (up to date)
  * cookbook_file[jenkins.model.DownloadSettings.xml] action create (up to date)
Recipe: artifactory::default
  * yum_package[unzip] action install (up to date)
  * linux_user[artifactory] action create (up to date)
  * directory[/var/lib/artifactory] action create (up to date)
  * directory[/var/lib/artifactory/tomcat] action create (up to date)
  * directory[/var/lib/artifactory/tomcat/work] action create (up to date)
  * directory[/var/lib/artifactory/tomcat/temp] action create (up to date)
  * directory[/var/lib/artifactory/logs] action create (up to date)
  * ark[artifactory] action install
    * directory[/usr/local/artifactory-1] action create (up to date)
    * remote_file[/var/chef/cache/artifactory-1.zip] action create (up to date)
    * execute[unpack /var/chef/cache/artifactory-1.zip] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/artifactory-1] action nothing (skipped due to action :nothing)
    * link[/usr/local/artifactory] action create (up to date)
    * template[/etc/profile.d/artifactory.sh] action create (skipped due to only_if)
    * ruby_block[adding '/usr/local/artifactory-1/bin' to chef-client ENV['PATH']] action run (skipped due to only_if)
     (up to date)
  * link[/var/lib/artifactory/webapps] action create (up to date)
  * link[/var/lib/artifactory/tomcat/logs] action create (up to date)
  * link[/var/lib/artifactory/tomcat/conf] action create (up to date)
  * template[/usr/local/artifactory/tomcat/conf/server.xml] action create (up to date)
Recipe: <Dynamically Defined Resource>
  * service[artifactory] action nothing (skipped due to action :nothing)
Recipe: artifactory::default
  * runit_service[artifactory] action enable
    * directory[/etc/sv/artifactory] action create (up to date)
    * template[/etc/sv/artifactory/run] action create (up to date)
    * directory[/etc/sv/artifactory/log] action create (up to date)
    * directory[/etc/sv/artifactory/log/main] action create (up to date)
    * template[/etc/sv/artifactory/log/run] action create (up to date)
    * template[/etc/sv/artifactory/log/config] action create (up to date)
    * directory[/etc/sv/artifactory/env] action create (up to date)
    * ruby_block[zap extra env files] action run (skipped due to only_if)
    * directory[/etc/sv/artifactory/control] action create (up to date)
    * link[/etc/init.d/artifactory] action create (up to date)
    * file[/etc/sv/artifactory/down] action nothing (skipped due to action :nothing)
    * link[/etc/service/artifactory] action create (up to date)
     (up to date)
Recipe: scala-jenkins-infra::_config-adminKeys
  * directory[/home/ec2-user/.ssh] action create (up to date)
  * file[/home/ec2-user/.ssh/authorized_keys] action create (up to date)
Recipe: scala-jenkins-infra::_master-config-proxy
  * yum_package[nginx] action install (up to date)
  * linux_user[nginx] action create (up to date)
  * template[/etc/nginx/nginx.conf] action create (up to date)
  * template[/etc/nginx/conf.d/jenkins.conf] action create (up to date)
  * directory[/etc/nginx/ssl] action create (up to date)
  * cookbook_file[scala-ci.crt] action create (up to date)
  * cookbook_file[dhparam.pem] action create (up to date)
  * file[/etc/nginx/ssl/scala-ci.key] action create (up to date)
  * service[nginx] action start (up to date)
Recipe: scala-jenkins-infra::_master-config-jenkins
  * ruby_block[set private key] action run
    - execute the ruby block set private key
  * template[/var/lib/jenkins/users/chef/config.xml] action create (up to date)
  * jenkins_plugin[notification] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/update-center.json] action create (up to date)
    * file[/var/chef/cache/extracted-update-center.json] action create (up to date)
     (up to date)
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[ssh-credentials] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/ssh-credentials-1.13.plugin] action create (up to date)
    * remote_file[/var/chef/cache/jenkins-cli.jar] action create (up to date)
    * file[/var/chef/cache/jenkins-key] action create (up to date)
    - Upgrade jenkins_plugin[ssh-credentials] from 1.10 to 1.13
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[groovy] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/groovy-2.0.plugin] action create (up to date)
    - Upgrade jenkins_plugin[groovy] from 1.30 to 2.0
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[cygpath] action install (up to date)
  * jenkins_plugin[job-dsl] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/job-dsl-1.63.plugin] action create (up to date)
    - Upgrade jenkins_plugin[job-dsl] from 1.57 to 1.63
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[rebuild] action install (up to date)
  * jenkins_plugin[greenballs] action install (up to date)
  * jenkins_plugin[build-timeout] action install (up to date)
  * jenkins_plugin[copyartifact] action install (up to date)
  * jenkins_plugin[email-ext] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/email-ext-2.57.2.plugin] action create (up to date)
    - Upgrade jenkins_plugin[email-ext] from 2.55 to 2.57.2
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[slack] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/slack-2.2.plugin] action create (up to date)
    - Upgrade jenkins_plugin[slack] from 2.1 to 2.2
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[throttle-concurrents] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/workflow-api-2.12.plugin] action create
      - create new file /var/chef/cache/workflow-api-2.12.plugin
      - update content in file /var/chef/cache/workflow-api-2.12.plugin from none to d83e61
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.8.plugin] action create
      - create new file /var/chef/cache/workflow-api-2.8.plugin
      - update content in file /var/chef/cache/workflow-api-2.8.plugin from none to d83e61
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.11.plugin] action create
      - create new file /var/chef/cache/workflow-api-2.11.plugin
      - update content in file /var/chef/cache/workflow-api-2.11.plugin from none to d83e61
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-support-2.13.plugin] action create
      - create new file /var/chef/cache/workflow-support-2.13.plugin
      - update content in file /var/chef/cache/workflow-support-2.13.plugin from none to 7e1d54
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/durable-task-1.14.plugin] action create
      - create new file /var/chef/cache/durable-task-1.14.plugin
      - update content in file /var/chef/cache/durable-task-1.14.plugin from none to 52c0ec
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-durable-task-step-2.8.plugin] action create
      - create new file /var/chef/cache/workflow-durable-task-step-2.8.plugin
      - update content in file /var/chef/cache/workflow-durable-task-step-2.8.plugin from none to b47568
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.11.plugin] action create (up to date)
    * remote_file[/var/chef/cache/workflow-support-2.13.plugin] action create (up to date)
    * remote_file[/var/chef/cache/throttle-concurrents-2.0.1.plugin] action create
      - create new file /var/chef/cache/throttle-concurrents-2.0.1.plugin
      - update content in file /var/chef/cache/throttle-concurrents-2.0.1.plugin from none to 626ebc
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[throttle-concurrents] from 1.9.0 to 2.0.1
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[dashboard-view] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/dashboard-view-2.9.11.plugin] action create
      - create new file /var/chef/cache/dashboard-view-2.9.11.plugin
      - update content in file /var/chef/cache/dashboard-view-2.9.11.plugin from none to ac5397
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[dashboard-view] from 2.9.10 to 2.9.11
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[parameterized-trigger] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/parameterized-trigger-2.34.plugin] action create
      - create new file /var/chef/cache/parameterized-trigger-2.34.plugin
      - update content in file /var/chef/cache/parameterized-trigger-2.34.plugin from none to feecd8
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[parameterized-trigger] from 2.32 to 2.34
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[ansicolor] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/ansicolor-0.5.0.plugin] action create (up to date)
    - Upgrade jenkins_plugin[ansicolor] from 0.4.3 to 0.5.0
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[github] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/github-1.27.0.plugin] action create
      - create new file /var/chef/cache/github-1.27.0.plugin
      - update content in file /var/chef/cache/github-1.27.0.plugin from none to 11038b
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[github] from 1.26.0 to 1.27.0
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[github-api] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/jackson2-api-2.7.3.plugin] action create
      - create new file /var/chef/cache/jackson2-api-2.7.3.plugin
      - update content in file /var/chef/cache/jackson2-api-2.7.3.plugin from none to 6dfa1b
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/github-api-1.85.1.plugin] action create
      - create new file /var/chef/cache/github-api-1.85.1.plugin
      - update content in file /var/chef/cache/github-api-1.85.1.plugin from none to a4c866
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[github-api] from 1.84 to 1.85.1
Recipe: scala-jenkins-infra::_master-config-jenkins
  * jenkins_plugin[github-oauth] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/github-branch-source-1.9.plugin] action create
      - create new file /var/chef/cache/github-branch-source-1.9.plugin
      - update content in file /var/chef/cache/github-branch-source-1.9.plugin from none to cfe30b
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.15.plugin] action create
      - create new file /var/chef/cache/workflow-api-2.15.plugin
      - update content in file /var/chef/cache/workflow-api-2.15.plugin from none to 970d02
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.16.plugin] action create
      - create new file /var/chef/cache/workflow-api-2.16.plugin
      - update content in file /var/chef/cache/workflow-api-2.16.plugin from none to 970d02
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-scm-step-2.4.plugin] action create
      - create new file /var/chef/cache/workflow-scm-step-2.4.plugin
      - update content in file /var/chef/cache/workflow-scm-step-2.4.plugin from none to 69d58c
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.11.plugin] action create
      - update content in file /var/chef/cache/workflow-api-2.11.plugin from d83e61 to 970d02
      (current file is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-support-2.14.plugin] action create
      - create new file /var/chef/cache/workflow-support-2.14.plugin
      - update content in file /var/chef/cache/workflow-support-2.14.plugin from none to 49bf65
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/ace-editor-1.0.1.plugin] action create
      - create new file /var/chef/cache/ace-editor-1.0.1.plugin
      - update content in file /var/chef/cache/ace-editor-1.0.1.plugin from none to d961d2
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/jquery-detached-1.2.1.plugin] action create
      - create new file /var/chef/cache/jquery-detached-1.2.1.plugin
      - update content in file /var/chef/cache/jquery-detached-1.2.1.plugin from none to a05273
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-cps-2.32.plugin] action create
      - create new file /var/chef/cache/workflow-cps-2.32.plugin
      - update content in file /var/chef/cache/workflow-cps-2.32.plugin from none to c280fc
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-api-2.11.plugin] action create (up to date)
    * remote_file[/var/chef/cache/workflow-support-2.14.plugin] action create (up to date)
    * remote_file[/var/chef/cache/workflow-job-2.10.plugin] action create
      - create new file /var/chef/cache/workflow-job-2.10.plugin
      - update content in file /var/chef/cache/workflow-job-2.10.plugin from none to fd5d5a
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-scm-step-2.4.plugin] action create (up to date)
    * remote_file[/var/chef/cache/workflow-api-2.11.plugin] action create (up to date)
    * remote_file[/var/chef/cache/workflow-support-2.14.plugin] action create (up to date)
    * remote_file[/var/chef/cache/cloudbees-folder-6.0.1.plugin] action create
      - create new file /var/chef/cache/cloudbees-folder-6.0.1.plugin
      - update content in file /var/chef/cache/cloudbees-folder-6.0.1.plugin from none to aeaec9
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/branch-api-2.0.7.plugin] action create
      - create new file /var/chef/cache/branch-api-2.0.7.plugin
      - update content in file /var/chef/cache/branch-api-2.0.7.plugin from none to 656d4b
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/cloudbees-folder-5.18.plugin] action create
      - create new file /var/chef/cache/cloudbees-folder-5.18.plugin
      - update content in file /var/chef/cache/cloudbees-folder-5.18.plugin from none to aeaec9
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/workflow-multibranch-2.9.plugin] action create
      - create new file /var/chef/cache/workflow-multibranch-2.9.plugin
      - update content in file /var/chef/cache/workflow-multibranch-2.9.plugin from none to 729c9a
      (new content is binary, diff output suppressed)
    * remote_file[/var/chef/cache/github-oauth-0.27.plugin] action create
      - create new file /var/chef/cache/github-oauth-0.27.plugin
      - update content in file /var/chef/cache/github-oauth-0.27.plugin from none to 3a7bb6
      (new content is binary, diff output suppressed)
    - Upgrade jenkins_plugin[github-oauth] from 0.25 to 0.27
Recipe: jenkins::_master_war
  * runit_service[jenkins] action restart (up to date)
Recipe: scala-jenkins-infra::_master-jenkins-auth-github
  * jenkins_script[add_gh_authentication] action execute
    
    ================================================================================
    Error executing action `execute` on resource 'jenkins_script[add_gh_authentication]'
    ================================================================================
    
    Jenkins::Helper::JenkinsNotReady
    --------------------------------
    The Jenkins master at `http://localhost:8080' did not become ready within 60
    seconds. On large Jenkins instances, you may need to increase the timeout to
    240 seconds. Alternatively, Jenkins may have failed to start.
    Jenkins can fail to start if:
    
      - a configuration file is invalid
      - a plugin is only partially installed
      - a plugin's dependencies are not installed
    
    If this problem persists, check your Jenkins log files.
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:424:in `rescue in wait_until_ready!'
    /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:404:in `wait_until_ready!'
    /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:61:in `executor'
    /var/chef/cache/cookbooks/jenkins/libraries/script.rb:53:in `block (2 levels) in <class:JenkinsScript>'
    /var/chef/cache/cookbooks/jenkins/libraries/script.rb:52:in `block in <class:JenkinsScript>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/scala-jenkins-infra/recipes/_master-jenkins-auth-github.rb
    
     13: jenkins_script 'add_gh_authentication' do
     14:   command <<-EOH.gsub(/^ {4}/, '')
     15:     import jenkins.model.Jenkins
     16:     import org.jenkinsci.plugins.*
     17: 
     18:     def githubRealm = new GithubSecurityRealm(
     19:       '#{node['master']['github']['webUri']}',
     20:       '#{node['master']['github']['apiUri']}',
     21:       '#{apiVault['client-id']}',
     22:       '#{apiVault['client-secret']}',
     23:       '#{node['master']['github']['oauthScopes']}')
     24: 
     25:     def githubStrategy = new GithubAuthorizationStrategy(
     26:       '#{node['master']['github']['adminUserNames']}',
     27:       #{node['master']['github']['authenticatedUserReadPermission']},
     28:       #{node['master']['github']['useRepositoryPermissions']},
     29:       #{node['master']['github']['authenticatedUserCreateJobPermission']},
     30:       '#{node['master']['github']['organizationNames']}',
     31:       #{node['master']['github']['allowGithubWebHookPermission']},
     32:       #{node['master']['github']['allowCcTrayPermission']},
     33:       #{node['master']['github']['allowAnonymousReadPermission']},
     34:       #{node['master']['github']['allowAnonymousJobStatusPermission']})
     35: 
     36:     Jenkins.instance.setSecurityRealm(githubRealm)
     37:     Jenkins.instance.setAuthorizationStrategy(githubStrategy)
     38:     Jenkins.instance.save()
     39:   EOH
     40: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/scala-jenkins-infra/recipes/_master-jenkins-auth-github.rb:13:in `from_file'
    
    jenkins_script("add_gh_authentication") do
      action [:execute]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_script
      cookbook_name "scala-jenkins-infra"
      recipe_name "_master-jenkins-auth-github"
      command "import jenkins.model.Jenkins\nimport org.jenkinsci.plugins.*\n\ndef githubRealm = new GithubSecurityRealm(\n  'https://github.com/',\n  'https://api.github.com',\n  '26e9d4f5aade76d0dfc2',\n  'd1c942320550c28748af2bd8cd641b46d6564aaf',\n  'read:org,user:email')\n\ndef githubStrategy = new GithubAuthorizationStrategy(\n  'adriaanm, retronym, lrytz, SethTisue, smarter, DarkDimius, chef, scala-jenkins, szeiger, dwijnand',\n  true,\n  true,\n  false,\n  'scala',\n  true,\n  false,\n  true,\n  true)\n\nJenkins.instance.setSecurityRealm(githubRealm)\nJenkins.instance.setAuthorizationStrategy(githubStrategy)\nJenkins.instance.save()\n"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2017-06-19T22:46:23+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-19T22:46:23+00:00] ERROR: Exception handlers complete
Chef Client failed. 40 resources updated in 03 minutes 27 seconds
[2017-06-19T22:46:23+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-06-19T22:46:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-19T22:46:23+00:00] ERROR: jenkins_script[add_gh_authentication] (scala-jenkins-infra::_master-jenkins-auth-github line 13) had an error: Jenkins::Helper::JenkinsNotReady: The Jenkins master at `http://localhost:8080' did not become ready within 60
seconds. On large Jenkins instances, you may need to increase the timeout to
240 seconds. Alternatively, Jenkins may have failed to start.
Jenkins can fail to start if:

  - a configuration file is invalid
  - a plugin is only partially installed
  - a plugin's dependencies are not installed

If this problem persists, check your Jenkins log files.

[2017-06-19T22:46:23+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by SethTisue** [comment]
ugh. we may need to pin the GitHub plugins, or all the plugins, to older versions

**Comment by SethTisue** [comment]
Adriaan got Jenkins back up for the time being, by manually fiddling with plugin versions, but we'll have to come back to this tomorrow and make sure `chef-client` is again safe to run
