### ISSUE TITLE
regression: Jenkins can't send email

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-jenkins-infra#246]
seen at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/951/consoleFull

```
Sending e-mails to: adriaan@lightbend.com seth.tisue@lightbend.com
ERROR: Could not connect to SMTP host: localhost, port: 25
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:131)
	at hudson.tasks.Mailer.perform(Mailer.java:170)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1752)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	... 18 more
```

**Comment by adriaanm** [comment]
I spent a few hours reading on how to configure, say, exim4 to only send email to addresses `@lightbend.com` (to avoid somehow becoming a spam relay when someone manages to run a shell script on the jenkins master). Then I ran out of time. I'd like someone else to look into this, but please make sure it's more secure than the default install.

**Comment by SethTisue** [comment]
![i am jenkins this is my new body](https://user-images.githubusercontent.com/161079/40820356-dcd748f4-6514-11e8-91c3-64f181418b90.jpg)

**Comment by SethTisue** [comment]
we've managed to live without this, especially with the advent of Travis-CI and GitHub Actions
