### ISSUE TITLE
Intermittent "Slave went offline during the build"

### ISSUE THREAD

**Issue by retronym** [scala/scala-jenkins-infra#26]
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/71/console

```
015-02-03 15:00:46,014 DEBUG [main] - ScalaPlugin - package fragment added or removed: src
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - javabootclasspath: /usr/lib/jvm/jdk1.6.0_45/jre/lib/resources.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/rt.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/jce.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.6.0_45/jre/lib/ext/sunpkcs11.jar
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - javaextdirs:  
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - scalabootclasspath: /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/m2repo/p2/osgi/bundle/org.scala-lang.scala-library/2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3/org.scala-lang.scala-library-2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3.jar
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - user classpath: /home/jenkins/workspace/scala-2.11.x-integrate-ide/target/m2repo/p2/osgi/bundle/org.scala-lang.scala-reflect/2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3/org.scala-lang.scala-reflect-2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3.jar:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/m2repo/p2/osgi/bundle/org.scala-lang.scala-actors/2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3/org.scala-lang.scala-actors-2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3.jar:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/m2repo/p2/osgi/bundle/org.scala-lang.scala-library/2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3/org.scala-lang.scala-library-2.11.6.v20150203-141730-da51dc9-SNAPSHOT-da51dc96f3.jar
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Sorry, this connection is closed.
    at com.trilead.ssh2.transport.TransportManager.ensureConnected(TransportManager.java:587)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:660)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:407)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:347)
    at com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:943)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:79)
    at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
    at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
    at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
    at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
Caused by: java.net.SocketException: Connection timed out
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at com.trilead.ssh2.crypto.cipher.CipherOutputStream.flush(CipherOutputStream.java:75)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:193)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:107)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:677)
    at com.trilead.ssh2.channel.ChannelManager.sendData(ChannelManager.java:429)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:63)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:68)
    at hudson.remoting.ChunkedOutputStream.sendFrame(ChunkedOutputStream.java:93)
    at hudson.remoting.ChunkedOutputStream.sendBreak(ChunkedOutputStream.java:66)
    at hudson.remoting.ChunkedCommandTransport.writeBlock(ChunkedCommandTransport.java:46)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.write(AbstractSynchronousByteArrayCommandTransport.java:45)
    at hudson.remoting.Channel.send(Channel.java:553)
    at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:279)
    at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
    at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Build step 'Execute shell' marked build as failure
ERROR: Publisher hudson.tasks.ArtifactArchiver aborted due to exception
hudson.AbortException: no workspace for scala-2.11.x-integrate-ide #71
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:72)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1743)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
ERROR: Publisher hudson.tasks.Mailer aborted due to exception
hudson.AbortException: no workspace for scala-2.11.x-integrate-ide #71
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:72)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1743)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - [StandardCompletionTests$] initializing -deprecation to false (false)
2015-02-03 15:00:46,064 DEBUG [main] - ScalaProject - [StandardCompletionTests$] initializing -feature to false (false)
```

**Comment by adriaanm** [comment]
Saw this again today. Three builds on the same worker were all aborted near the end of the build for unexplained reasons.  Here's two of them:
https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/106/console
https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/107/consoleFull

Is it the copy artifact plugin? (FlightRecorderInputStream)

I suspect https://issues.jenkins-ci.org/browse/JENKINS-22816

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/137/console

**Comment by adriaanm** [comment]
```
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Build step 'Execute shell' marked build as failure
ERROR: Publisher hudson.tasks.ArtifactArchiver aborted due to exception
hudson.AbortException: no workspace for scala-2.11.x-validate-test #161
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:72)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1743)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
```

https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/161/console

in scala/scala#4312

**Comment by adriaanm** [comment]
I turned off "response time monitoring" for the workers, to see if that helps. ![screenshot](https://www.dropbox.com/s/cknsy16q73k5pzd/Screenshot%202015-02-10%2009.26.02.png?dl=1)

Based on http://stackoverflow.com/questions/9998298/jenkins-slave-jobs-failing-on-unexpected-termination-of-channel#comment24912130_9998520

**Comment by adriaanm** [comment]
I'm wondering whether the EC2 instance actually went down:

Jenkins logs:

```
Feb 10, 2015 5:41:16 PM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted connection #7004 from /127.0.0.1:37788
Feb 10, 2015 6:00:26 PM WARNING hudson.remoting.ProxyOutputStream$Chunk$1 run
Failed to ack the stream
java.net.SocketException: Connection timed out
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at com.trilead.ssh2.crypto.cipher.CipherOutputStream.flush(CipherOutputStream.java:75)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:193)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:107)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:677)
    at com.trilead.ssh2.channel.ChannelManager.sendData(ChannelManager.java:429)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:63)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:68)
    at hudson.remoting.ChunkedOutputStream.sendFrame(ChunkedOutputStream.java:93)
    at hudson.remoting.ChunkedOutputStream.sendBreak(ChunkedOutputStream.java:66)
    at hudson.remoting.ChunkedCommandTransport.writeBlock(ChunkedCommandTransport.java:46)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.write(AbstractSynchronousByteArrayCommandTransport.java:45)
    at hudson.remoting.Channel.send(Channel.java:553)
    at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:279)
    at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
    at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Feb 10, 2015 6:00:26 PM SEVERE hudson.remoting.SynchronousCommandTransport$ReaderThread run
I/O error in channel jenkins-worker-behemoth-2
java.io.IOException: Sorry, this connection is closed.
    at com.trilead.ssh2.transport.TransportManager.ensureConnected(TransportManager.java:587)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:660)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:407)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:347)
    at com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:943)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:79)
    at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
    at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
    at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
    at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
Caused by: java.net.SocketException: Connection timed out
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at com.trilead.ssh2.crypto.cipher.CipherOutputStream.flush(CipherOutputStream.java:75)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:193)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:107)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:677)
    at com.trilead.ssh2.channel.ChannelManager.sendData(ChannelManager.java:429)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:63)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:68)
    at hudson.remoting.ChunkedOutputStream.sendFrame(ChunkedOutputStream.java:93)
    at hudson.remoting.ChunkedOutputStream.sendBreak(ChunkedOutputStream.java:66)
    at hudson.remoting.ChunkedCommandTransport.writeBlock(ChunkedCommandTransport.java:46)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.write(AbstractSynchronousByteArrayCommandTransport.java:45)
    at hudson.remoting.Channel.send(Channel.java:553)
    at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:279)
    at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
    at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Feb 10, 2015 6:00:26 PM WARNING hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor monitor
Failed to monitor jenkins-worker-behemoth-2 for Architecture
hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.Channel.send(Channel.java:549)
    at hudson.remoting.Request.callAsync(Request.java:204)
    at hudson.remoting.Channel.callAsync(Channel.java:778)
    at hudson.node_monitors.AbstractAsyncNodeMonitorDescriptor.monitor(AbstractAsyncNodeMonitorDescriptor.java:76)
    at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:302)
Caused by: java.io.IOException: Sorry, this connection is closed.
```

The status check passed at 6:01 PM, but then no data.... ![screenshot](https://www.dropbox.com/s/x43881s64vm0imq/Screenshot%202015-02-10%2011.40.59.png?dl=1)

**Comment by adriaanm** [comment]
Not sure what to make of all this. Did the ec2 node go down (maybe because a bug in the idle mechanism that then stops the ec2 node?), causing the jenkins master to lose the connection to the worker, or did it go down because Jenkins took the worker offline when it timed out (because it thought it couldn't reach it) and that caused the ec2 node to be stopped.... 

Others are [reporting similar symptoms](https://issues.jenkins-ci.org/browse/JENKINS-14332?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel) and blame the linux kernel. We are running the same kernel version as reported by those having problems: `Linux jenkins-master 3.14.20-20.44.amzn1.x86_64`

**Comment by adriaanm** [comment]
Another (outlandish) theory is that it's chef-client interfering with jenkins: it runs every 30 minutes, and did run around the time of the failure (/var/log/chef/client.log)

**Comment by adriaanm** [comment]
as suggested by @retronym, our next diagnostic step could be to include a background script in the job runner that logs cpu load to a file, or even better, intersperses it with the job's output

**Comment by adriaanm** [comment]
The kernel hypothesis just become more plausible. See https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811

from /var/log/messages:

```
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.037339] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.040807] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.043566] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.046323] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.050243] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.053073] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.055897] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.059566] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:44:59 ip-172-31-2-59 kernel: [1618769.062282] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:45:05 ip-172-31-2-59 kernel: [1618775.824098] net_ratelimit: 62 callbacks suppressed
Feb 10 17:45:05 ip-172-31-2-59 kernel: [1618775.826108] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:45:12 ip-172-31-2-59 kernel: [1618782.240092] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:45:25 ip-172-31-2-59 kernel: [1618795.072102] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:45:50 ip-172-31-2-59 kernel: [1618820.704092] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:46:42 ip-172-31-2-59 kernel: [1618872.032091] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:48:24 ip-172-31-2-59 kernel: [1618974.688093] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:50:25 ip-172-31-2-59 kernel: [1619095.008107] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:52:25 ip-172-31-2-59 kernel: [1619215.328095] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:54:25 ip-172-31-2-59 kernel: [1619335.648103] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:56:13 ip-172-31-2-59 dhclient[1916]: DHCPREQUEST on eth0 to 172.31.0.1 port 67 (xid=0x158cb3f)
Feb 10 17:56:13 ip-172-31-2-59 dhclient[1916]: DHCPACK from 172.31.0.1 (xid=0x158cb3f)
Feb 10 17:56:15 ip-172-31-2-59 dhclient[1916]: bound to 172.31.2.59 -- renewal in 1620 seconds.
Feb 10 17:56:26 ip-172-31-2-59 kernel: [1619455.968093] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 17:58:26 ip-172-31-2-59 kernel: [1619576.288290] xen_netfront: xennet: skb rides the rocket: 20 slots
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: Feb 10, 2015 6:00:26 PM hudson.remoting.ProxyOutputStream$Chunk$1 run
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: WARNING: Failed to ack the stream
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: #011at java.net.SocketOutputStream.socketWrite0(Native Method)
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: #011at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)

```

**Comment by adriaanm** [comment]
Note that jenkins master is not running ubuntu, but it's the same kernel.

**Comment by adriaanm** [comment]
I updated to the latest kernel available on amazon linux, but no way of telling whether this bug is fixed.. probably not... Maybe we should switch to ubuntu.

**Comment by adriaanm** [comment]
I have enabled the workaround from https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811/comments/22. Let's see whether that does the trick.

```
[root@ip-172-31-2-59 ec2-user]# ethtool -K eth0 sg off
Actual changes:
scatter-gather: off
    tx-scatter-gather: off
tcp-segmentation-offload: off
    tx-tcp-segmentation: off [requested on]
generic-segmentation-offload: off [requested on]
```

**Comment by retronym** [comment]
:pray:

**Comment by adriaanm** [comment]
I looked through the sources of the kernel we're running, but it doesn't have the file that had the bug, so not sure how to find out whether we need the workaround.

**Comment by adriaanm** [comment]
We've been SocketException-free since the workaround was activated -- looks like the :pray:ers were heard!

```
ec2-user@ip-172-31-2-59 ~]$ sudo grep SocketException /var/log/messages
Feb  8 22:18:43 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb  8 22:18:43 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb  8 22:18:43 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb  8 22:18:43 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb  8 22:18:43 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb  9 02:23:17 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb  9 02:23:17 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 10:27:35 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 10:27:35 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 11:18:19 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 11:18:19 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 13:06:20 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 14:42:59 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 14:42:59 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: java.net.SocketException: Connection timed out
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
Feb 10 18:00:26 ip-172-31-2-59 [jenkins]: Caused by: java.net.SocketException: Connection timed out
```

**Comment by adriaanm** [comment]
48 hours without symptoms seems like enough to declare the patient cured.

**Comment by adriaanm** [comment]
Hallelujah, praise the 4df3f01!
