### ISSUE TITLE
builds aborted due to time out in agent connection?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#28]
Three builds on the same worker were all aborted near the end of the build for unexplained reasons.  Is it the copy artifact plugin? (FlightRecorderInputStream)

Here's two of them:
https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/106/console
https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/107/consoleFull

```
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Sorry, this connection is closed.
    at com.trilead.ssh2.transport.TransportManager.ensureConnected(TransportManager.java:587)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:660)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:407)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:347)
    at com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:943)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
    at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:79)
    at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
    at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
    at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
    at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
Caused by: java.net.SocketException: Connection timed out
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at com.trilead.ssh2.crypto.cipher.CipherOutputStream.flush(CipherOutputStream.java:75)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:193)
    at com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.java:107)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:677)
    at com.trilead.ssh2.channel.ChannelManager.sendData(ChannelManager.java:429)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:63)
    at com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:68)
    at hudson.remoting.ChunkedOutputStream.sendFrame(ChunkedOutputStream.java:93)
    at hudson.remoting.ChunkedOutputStream.sendBreak(ChunkedOutputStream.java:66)
    at hudson.remoting.ChunkedCommandTransport.writeBlock(ChunkedCommandTransport.java:46)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.write(AbstractSynchronousByteArrayCommandTransport.java:45)
    at hudson.remoting.Channel.send(Channel.java:553)
    at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:279)
    at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:18)
    at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Build step 'Execute shell' marked build as failure
ERROR: Publisher hudson.tasks.ArtifactArchiver aborted due to exception
hudson.AbortException: no workspace for scala-2.11.x-validate-test #107
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:72)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1743)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
```

**Comment by adriaanm** [comment]
duplicate of #26
